const SMS_STATUSES = {
  SENT: "SENT",
  FAILED: "FAILED",
  DELIVERED: "DELIVERED",
  RATE_LIMITED: "RATE_LIMITED",
};

const AUTH_ERRORS = {
  INVALID_PASSWORD: "INVALID_PASSWORD",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  NOT_LOGGED_IN: "NOT_LOGGED_IN",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  USER_EXISTS: "USER_EXISTS",
  INVALID_NAME: "INVALID_NAME",
};

const SMS_ERRORS = {
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  MISSING_MESSAGE: "MISSING_MESSAGE",
};

const ERROR_FIELDS = {
  PASSWORD: "password",
  PHONE_NUMBER: "phoneNumber",
  NAME: "name",
  MESSAGE: "message",
  TOAST: "toast",
};

const MAX_SMS_PER_MINUTE = 3;
const MAX_SMS_PER_DAY = 10;

module.exports = {
  SMS_STATUSES,
  AUTH_ERRORS,
  SMS_ERRORS,
  ERROR_FIELDS,
  MAX_SMS_PER_DAY,
  MAX_SMS_PER_MINUTE,
};
